name=input("Name:")
surname=('surname:')
age=int(input("age:"))
birth1=int(input("day:"))
birth2=int(input("month:"))
birth3=int(input("year:"))
print("=====================")
print(name)
print(surname)
print(age)
print(birth1, "/" ,birth2 ,"/",birth3)
print("=====================")